language: python
python: 2.7
sudo: false
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=flake8
install: pip install -U tox
script: tox
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
